version: '3.1'

services:
  docidx:
    image: docidx:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8005:8005"
    #command: python main.py
    command: flask run -h 0.0.0.0 -p 8005